---
layout: cv
title: Darren Chambers Resume
---
# Darren Chambers
Ambitious Computer Science student with a strong foundation in data analysis, visualization, and machine learning. Eager to leverage technical expertise, experience in the military, and a creative mindset to address challenging problems in artificial intelligence and beyond.

<div id="webaddress">
<a href="darrenc.chambers@gmail.com">darrenc.chambers@gmail.com</a>
| <a href="https://www.linkedin.com/in/darren-chambers-4a3397b5/">My linkedin page</a>
</div>


## Skills

Technical: Python, Pandas, Plotly.express, NumPy, XGBoost, Scikit-learn
Soft Skills: Team Leadership, Strategic Thinking, Effective Communication
Languages: French (Proficient), Spanish (Basic), Japanese (Basic)

### Education

Brigham Young University – Idaho Bachelor of Science in Computer Science (Spring 2025)


### Academic Projects

Developed a data visualization project focusing on human trafficking, using Python and Plotly.express to create interactive charts and maps, which was recognized for its innovative approach to data presentation at Hack USU 2024
Led the development of an application/website for Amber Alerts, integrating real-time mapping and alerts, targeting a local community program to help child recovery.


## Work Experience

`2024`
__Brigham Young University-Idaho – Python Teaching Assistant ( 6 months )__
Designed and conducted additional tutorial sessions for students struggling
with Python programming, leading to an improvement in grades.

`2019-2023`
__US Army Airborne Infantry (4 years)__

- In a high-stakes environment ensured the safety and efficiency of equipment worth over $200,000.
Mentored new personnel, fostering their professional development and ensuring accurate management of their administrative tasks.


## Volunteer Experience

__Full-time Missionary in Montreal, Canada__
The Church of Jesus Christ of Latter-day Saints (2 years)
Engaged in community service projects and cultural events, building lasting relationships and increasing community participation in church activities by a significant amount.

## Certifications
Ethical Hacking (Expected 2024)




<!-- ### Footer

Last updated: May 2013 -->